version: '3' 
services:
  web:
    restart: always #one of the restart policy
    build:
      context: .
      dockerfile: Dockerfile.dev
    user: node
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    user: node
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "test"]
